

export const ABOUT_DISABLE_LOADER = "ABOUT_DISABLE_LOADER";
export const LOGIN_FIRST_TIME = "LOGIN_FIRST_TIME";
export const GEOCODING_API = "GEOCODING_API";
export const REVERCE_GEOCODING_API = "REVERCE_GEOCODING_API";
export const ENABLE_LOADER = "ENABLE_LOADER";
export const SETFIRST_TIMEDATE = "SETFIRST_TIMEDATE";

export const REVERSE_RESPONSE = "REVERSE_RESPONSE";//SETFIRST_TIMEDATE

export const GECODE_RESPONSE = "GECODE_RESPONSE";
export const CAPTURE_DATA = "CAPTURE_DATA";
